AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lab 8: Infrastructure and Network Protection - Shield Advanced Configuration'

Parameters:
  Environment:
    Type: String
    Default: Lab8
    Description: Environment name for resource tagging
  EmailAddress:
    Type: String
    Description: Email address for DDoS notifications

Resources:
  # SNS Topic for Shield Notifications
  ShieldNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-shield-notifications
      DisplayName: Shield DDoS Notifications
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ShieldTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ShieldNotificationTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowShieldPublish
            Effect: Allow
            Principal:
              Service: shield.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ShieldNotificationTopic

  ShieldEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ShieldNotificationTopic
      Protocol: email
      Endpoint: !Ref EmailAddress

  # Shield Advanced Configuration
  ShieldProtection:
    Type: AWS::Shield::Protection
    Properties:
      Name: !Sub ${Environment}-shield-protection
      ResourceArn: !ImportValue
        'Fn::Sub': ${Environment}-ALB-ARN
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarms for Shield Events
  ShieldDDoSAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-Shield-DDoS-Detection
      AlarmDescription: Alarm when Shield detects a DDoS attack
      MetricName: DDoSDetected
      Namespace: AWS/Shield
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ShieldNotificationTopic
      OKActions:
        - !Ref ShieldNotificationTopic
      Dimensions:
        - Name: ResourceArn
          Value: !ImportValue
            'Fn::Sub': ${Environment}-ALB-ARN

  ShieldDDoSAttackBitsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-Shield-DDoS-AttackBits
      AlarmDescription: Alarm when Shield detects high volume of attack traffic
      MetricName: AttackBits
      Namespace: AWS/Shield
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000000000  # 1 Gbps
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ShieldNotificationTopic
      OKActions:
        - !Ref ShieldNotificationTopic
      Dimensions:
        - Name: ResourceArn
          Value: !ImportValue
            'Fn::Sub': ${Environment}-ALB-ARN

  ShieldDDoSAttackPacketsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-Shield-DDoS-AttackPackets
      AlarmDescription: Alarm when Shield detects high volume of attack packets
      MetricName: AttackPackets
      Namespace: AWS/Shield
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000000  # 1M packets per second
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ShieldNotificationTopic
      OKActions:
        - !Ref ShieldNotificationTopic
      Dimensions:
        - Name: ResourceArn
          Value: !ImportValue
            'Fn::Sub': ${Environment}-ALB-ARN

  # EventBridge Rule for Shield Events
  ShieldEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${Environment}-shield-events
      Description: Capture all Shield events
      EventPattern:
        source:
          - aws.shield
        detail-type:
          - AWS Shield DDoS Attack Detection
          - AWS Shield DDoS Attack Mitigation
      State: ENABLED
      Targets:
        - Arn: !Ref ShieldNotificationTopic
          Id: ShieldEvents

  # IAM Role for Shield Response Team
  ShieldResponseTeamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-shield-response-team
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: shield.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSShieldDRTAccessPolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ShieldNotificationTopicArn:
    Description: Shield Notification Topic ARN
    Value: !Ref ShieldNotificationTopic
    Export:
      Name: !Sub ${Environment}-Shield-Topic-ARN

  ShieldProtectionId:
    Description: Shield Protection ID
    Value: !Ref ShieldProtection
    Export:
      Name: !Sub ${Environment}-Shield-Protection-ID

  ShieldResponseTeamRoleArn:
    Description: Shield Response Team Role ARN
    Value: !GetAtt ShieldResponseTeamRole.Arn
    Export:
      Name: !Sub ${Environment}-Shield-Response-Team-Role-ARN 